### ISSUE TITLE
OWD project: add missing events

### ISSUE THREAD

**Issue by queengooborg** [openwebdocs/project#121]
Now that we have updated the event data to conform to the new structure in #61, it would be good to add the missing events.  In https://github.com/openwebdocs/project/issues/61#issuecomment-1192345470, @dontcallmedom mentioned a curated list of events from W3C:

> [We] have made good progress in collecting information about events from across specifications, with the current version of our work ready to be released as a package reviewable in https://raw.githubusercontent.com/w3c/webref/curated/ed/events.json with the guarantees described at https://github.com/w3c/webref/tree/curated/packages/events#guarantees

**Comment by Elchi3** [comment]
Thanks for filing an OWD project proposal!

I think this proposal needs to be a bit more information in order to be actionable for us. See also the [OWD prioritization criteria](https://github.com/openwebdocs/project/blob/main/steering-committee/prioritization-criteria.md) which guides us to make decisions.

### Effort
How much effort do you think this will be? What does "missing events" refer to exactly? I think we usually don't add events or web platform features to BCD and MDN that aren't implemented anywhere yet. Can you provide a list of missing event that are actually implemented that need docs/compat data?

### Dependencies
Do you think this project depends on having guidelines around how to add events to BCD? I think I oftentimes still struggle to add them to the correct interface (especially when events bubble).

### Community enablement
How would you make this project collaborative? (in case we are talking about many missing events, maybe more than 30). It would be nice to share the workload.

### Momentum 
If you provide a list of missing events, it would be nice to see about what sorts of events we are talking about here. Maybe it would be better to document certain APIs than to just document the events? For example, let's say missing events are for the WebTransport API, wouldn't it be better to the document the entire WebTransport API instead of just the events for that API? Again, I think we need the concrete list of events here in order to judge this work and its momentum.

**Comment by Elchi3** [comment]
Jean-Yves volunteered to write a new issue about follow up work for events but we are not planning to document missing events as outlined in this issue unless as useful list of missing event docs is provided. 

(useful list = events that are actually implemented, are missing from MDN and/or BCD, and aren't part of other projects for documenting new things [e.g. Web GPU will be documented on its own, no need to pick events from there and document them separately]).
