### ISSUE TITLE
OWD project: BCD updates for stable browser releases during Q4 2022

### ISSUE THREAD

**Issue by foolip** [openwebdocs/project#89]
After or in parallel with https://github.com/openwebdocs/project/issues/85, we should create a process for BCD maintenance.

In short, the process here would be to test each new ~~beta and~~ stable browser release with http://mdn-bcd-collector.appspot.com/ and updating BCD to be consistent with the results, on an ongoing basis.

@queengooborg WDYT?

**Comment by queengooborg** [comment]
+1 for this -- having an automated maintenance process for new browser releases would be very helpful!

**Comment by foolip** [comment]
@robnyman can you include this if Google's suggested priorities for OWD Q3 OKRs?

**Comment by robnyman** [comment]
@Elchi3 Right. Who'd be best then, since I probably won't be in those meetings. @wbamberg perhaps?

**Comment by teoli2003** [comment]
I've created a new label to flag potential projects for Q3 2022. We will see how good it will go! (We will consider this one)

**Comment by robnyman** [comment]
@teoli2003 That's great, thank you!

**Comment by foolip** [comment]
Q3 is starting soon, what is the planning process going to look like?

**Comment by queengooborg** [comment]
This has been added as a Q3 project (with myself as the assignee)!

**Comment by Elchi3** [comment]
Has this process been created? I see that @queengooborg filed PRs to add new web platform features to BCD recently. Can other people run that process, too? What is the plan here?

**Comment by foolip** [comment]
@queengooborg are you going to do an update for Safari 16? I just submitted 15.6 results that should help in https://github.com/foolip/mdn-bcd-results/pull/3192.

**Comment by Elchi3** [comment]
> Has this process been created? I see that @queengooborg filed PRs to add new web platform features to BCD recently. Can other people run that process, too? What is the plan here?

Vinyl told me that this issue is meant to continue throughout Q4 to update stable browser's data.
I think, more precisely, the tasks here to run the collector against BCD when the following releases have happened:

- [ ] Safari 16 (12th September 2022)
- [ ] Firefox 105 (20th September 2022)
- [ ] Chrome 106 (27th September 2022)
- [ ] Firefox 106 (18th October 2022)
- [ ] Chrome 107 (25th October 2022)
- [ ] Firefox 107 (15th November 2022)
- [ ] Chrome 108 (29th November 2022)
- [ ] Firefox 108 (13th December 2022)

Anything else?
 I'm going to add these tasks to our Q4 then.

**Comment by foolip** [comment]
There's also beta releases, which is mostly a matter of changing those dates. But once stable is released, we also need to check for contradictions in the results, in case something was reverted before stable.

**Comment by queengooborg** [comment]
> There's also beta releases, which is mostly a matter of changing those dates.

I don't think we should collect results for beta browser versions, for the very same reason that features are likely to be reverted or disabled in stable.  This is especially true for Firefox, which is known to enable flags in dev/nightly/beta releases that are disabled in stable.

> Has this process been created? [...] Can other people run that process, too?

The process has been around since the mdn-bcd-collector project was introduced, and anyone is able to run it with some slight differences from how @foolip and I do.  The general process is the following:

- Initial setup: Locally check out BCD, the collector and the results repos (preferably adjacent to each other)
- Run the collector website on the new browser version
- Submit the results to GitHub using the appropriate export button, then checkout the PR branch while waiting for merge
  - Alternatively, one can manually download the results to the results repo folder and manually submit a PR of their own
- Run the update-bcd script using `--browser=<browser_id> --release=<browser_version>`
- Start submitting BCD PRs from the changes made to the BCD local copy

**Comment by Elchi3** [comment]
In the planning call yesterday, we decided to take this on for stable browser releases as mentioned in my comment above. https://github.com/openwebdocs/project/issues/89#issuecomment-1245166605

**Comment by Elchi3** [comment]
> * Chrome 106 (27th September 2022)

So this was last week. How do we know if BCD has everything for Chrome 106? Has there been a PR to BCD?

**Comment by queengooborg** [comment]
I've now double-checked the status of this and submitted PRs for all remaining changes.  I omitted PRs for ones that I don't believe are accurate and need to be overridden in the collector results anyways (typically due to OS implementation discrepancies).  As such, I'm happy to say that this project is now done!

**Comment by Elchi3** [comment]
Well done, @queengooborg! 👍 We probably want to file a similar project for browser releases happening in Q1 2023.
